# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [12]:
print(A.ndim) # print dimension
print(A.shape) # print shape
print(A.size) # print size

2
(3, 5)
15


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [13]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [17]:
print(B - C) # Subtract B with C
print('------')
print(B * C) # Multiply B with C
print('------')
print(B @ C) # Multiply B with C (matrix product)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
------
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
------
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [21]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
print(np.exp(B)) # prints the exp for each element
print('---------------------------------------')
print(B.min()) # prints the smallest element
print('---------------------------------------')
print(B.min(axis=1)) # prints the smallest element for each row
print('---------------------------------------')
print(B.min(axis=0)) # prints the smallest element for each columns
print('---------------------------------------')
print(np.argmin(B)) # prints the index of the smallest element
print('---------------------------------------')
print(B.sum()) # prints the sum of all elements
print('---------------------------------------')
print(B.mean(axis=0)) # prints the mean of each column
print('---------------------------------------')
print(np.median(B,axis=0)) # prints median of each column

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
---------------------------------------
1
---------------------------------------
[1 4 7]
---------------------------------------
[1 2 3]
---------------------------------------
0
---------------------------------------
45
---------------------------------------
[4. 5. 6.]
---------------------------------------
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [41]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [44]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# When only providing only one index it's assumed that we want to see row with index 1 and ALL columns

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [45]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [46]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [50]:
for i in A:
    for e in i:
        print(e)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [49]:
# Eller denna:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [51]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
### a är en 1-dimensionell array med 30 element
### b är en 3-dimensionell array som skapats utifrån a. 2 yttre arrays som innehåller 3 arrays vardera. 
### -1 låter numpy själv räkna ut hur många element som ska vara i varje array.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [52]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [53]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [54]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [91]:
def add_mult_matrices(matrix_1, matrix_2, operand):
    # Check if matrices are of type ndarray
    if not isinstance(matrix_1, np.ndarray) or not isinstance(matrix_2, np.ndarray):
        raise TypeError('Two ndarrays need to be used.')
        # Check if operand is add
    if operand == 'add':
        # Check if the matrices have the same size
        if matrix_1.shape == matrix_2.shape:
            return matrix_1 + matrix_2
        else:
            raise ValueError('Matrix sizes are not the same. Add not possible.')
        # Check if operand is multiply
    elif operand == 'multiply':
        # Check if matrices have correct size column vs row
        if matrix_1.shape[1] == matrix_2.shape[0]:
            return matrix_1 @ matrix_2
        else:
            raise ValueError('Number of columns are not matching number of rows')
    # If neither add or multiply
    else:
        raise ValueError("Operand need to be 'add' or 'multiply")        

In [101]:
A = np.array([[1, 3, 5], [3, 5, 7]])
B = np.array([[0, 0, 4], [1, 6, 8]])
C = np.array([[1, 4], [2, 6]])
D = np.array([[2, 2], [5, 6]])

print(C.shape)
print(A.shape[0])
print(C.shape[1])
print(add_mult_matrices(A, B, 'add'))
print(add_mult_matrices(D, B, 'multiply'))


(2, 2)
2
2
[[ 1  3  9]
 [ 4 11 15]]
[[ 2 12 24]
 [ 6 36 68]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [135]:
### 10.1.1 a
x = np.array([[4,3]])
print(x.shape)

(1, 2)


In [109]:
# b
print(5 * x)

[[20 15]]


In [110]:
# c
print(3 * x)

[[12  9]]


In [112]:
# d
print(5 * x + 3 * x)

[[32 24]]


In [114]:
# e
print(8 * x)

[[32 24]]


In [115]:
# f
print(4 * x - x)

[[12  9]]


In [118]:
# g
print(x.T)
print(x.T.shape)

[[4]
 [3]]
(2, 1)


In [121]:
# h
# Svar: inte inom matematiken eftersom de inte har samma dimensioner, men numpy löser med broadcasting
print(x + x.T)

[[8 7]
 [7 6]]


In [120]:
# i
print(np.linalg.norm(x))

5.0


In [136]:
### 10.1.2 a
v = np.array([[3], [7], [0], [11]])
print(v.shape)

(4, 1)


In [126]:
# b
print(2 * v)

[[ 6]
 [14]
 [ 0]
 [22]]


In [127]:
# c
print(5 * v + 2 * v)

[[21]
 [49]
 [ 0]
 [77]]


In [128]:
# d
print(4 * v - 2 * v)

[[ 6]
 [14]
 [ 0]
 [22]]


In [130]:
# e
vt = v.T
print(vt)
print(vt.shape)

[[ 3  7  0 11]]
(1, 4)


In [131]:
# f
print(np.linalg.norm(v))

13.379088160259652


In [137]:
### 10.1.3 a
v1 = np.array([[4, 3, 1, 5]])
v2 = np.array([[2, 3, 1, 1]])
print(np.linalg.norm(v1))

7.14142842854285


In [138]:
# b
print(np.linalg.norm(v1 - v2))

4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [143]:
### 10.2.1

A = np.array([[2, 1, -1], 
              [1, -1, 1]])

B = np.array([[4, -2, 1], 
              [2, -4, -2]])

C = np.array([[1, 2], 
              [2, 1]])

D = np.array([[3, 4], 
              [4, 3]])

E = np.array([[1], 
              [2]])

I = np.array([[1, 0], 
              [0, 1]])

In [144]:
# a
print(2 * A)

[[ 4  2 -2]
 [ 2 -2  2]]


In [145]:
# b
print(B - 2 * A)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [147]:
# c - numpy kan hantera de olika dimensionerna med hjälp av broadcasting
print(3 * C - 2 * E)

[[ 1  4]
 [ 2 -1]]


In [148]:
# d
print(2 * D - 3 * C)

[[3 2]
 [2 3]]


In [149]:
# e
print(D.T + 2 * D)

[[ 9 12]
 [12  9]]


In [150]:
# f
print(2 * C.T - 2 * D.T)

[[-4 -4]
 [-4 -4]]


In [152]:
# g - går inte att broadcast, därför kan beräkning av olika dimensioner inte göras
print(A.T - B)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [162]:
# h - Går inte då A har tre kolumner och C har två rader, de måste vara samma
print(A @ C)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [160]:
# i
print(C @ D)

[[11 10]
 [10 11]]


In [161]:
# j
print(C @ B)

[[  8 -10  -3]
 [ 10  -8   0]]


In [163]:
# k
print(C @ I)

[[1 2]
 [2 1]]


In [164]:
# l
print(A @ B.T)

[[5 2]
 [7 4]]


In [167]:
### 10.2.2
A = np.array([[2, 3, 4], 
              [5, 4, 1]])
print(A @ A.T)

[[29 26]
 [26 42]]


In [173]:
### 10.2.3
A = np.array([[1, 2], 
              [2, 4]])

B = np.array([[2, 1], 
              [1, 3]])

C = np.array([[4, 3], 
              [0, 2]])

print(A @ B == A @ C)
print()
print(B == C)

[[ True  True]
 [ True  True]]

[[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [174]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [175]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [176]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
## Svar: The data buffer remains the same, so changes in the view will also reflect in the orginal copy.